title: OKE-advanced
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://achasan.github.io/oke-advanced

aux_links:
  Template Repository: https://github.com/Achasan/oke-advanced
